[package]
name = "chess_engine_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "chess_engine_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
numpy = "0.19"
shakmaty = "=0.25.0"
shakmaty-syzygy = "=0.23.0"
ndarray = "0.15"
