[build-system]
requires = ["maturin>=0.14,<0.16"]
build-backend = "maturin"

[project]
name = "chess_engine_core"
requires-python = ">=3.8"
version = "0.1.0"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
